### ISSUE TITLE
Concise CSS

### ISSUE THREAD

**Issue by aubreywullschleger** [quicksheep/prj-rev-bwfs-dasmoto#4]
Great! Good job with the concise CSS! Here I would make sure that you are using consistent spacing/indenting to make your CSS easier to read.  Also, I found your comments helpful as they helped me to understand why you were making the styling and general CSS decisions you were, but for production code I would remove those comments, again for the sake of readability.

**Comment by quicksheep** [comment]
Thanks for the note about killing comments for production sites.
