### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [quicksheep/prj-rev-bwfs-dasmoto#5]
Grade: Meets expectations

Summary:
Wonderful job on this projcet! I love your use of locally stored images, organized HTML, and concise CSS.

One thing to work on here would be making your CSS easier to read by using consistent spacing/indentation in your CSS and also removing the comments.

Next, as a stretch goal, I challenge you to research and implement media queries to make your page 100% responsive for all screen widths.  This is a challenge I think you are ready for based on your awesome work here!  Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by quicksheep** [comment]
Thanks for the great resource on queries for specific devices. *bookmarked*
